### PR TITLE
Update infrastructure for deploying

### PR DESCRIPTION
**Pull request by paulathevalley**
This PR updates the infrastructure for deploying, including pinning the `radium` dependency.

### CODE REVIEW

**Comment by paulathevalley** [comment]
This PR will depend on an upgrade to `builder-docs-archetype`: https://github.com/FormidableLabs/builder-docs-archetype/pull/41

**Comment by alexlande** [comment]
Sorry, forgot about this. Looks good as far as I can tell!

**Comment by paulathevalley** [comment]
@alexlande Do you want to include the changes from https://github.com/FormidableLabs/radium/pull/927? Since the radium dependency is now pinned, we'll need a new version of radium to include them.

**Comment by alexlande** [comment]
Oh, right. Let's hold off. I'll plan on publishing a new radium version soon, but not quite ready yet.

**Comment by ryan-roemer** [comment]
Conflicting and old, so closing.

**Pull request closed without merging**
